# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :VagrantVM1 do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.network :private_network, ip: "192.168.100.2"
    node.vm.provision "shell", path: "aprovisionadorVM1.sh"
    node.vm.hostname = "VagrantVM1"
  end

  config.vm.define :VagrantVM2 do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.network :private_network, ip: "192.168.100.3"
    node.vm.provision "shell", path: "aprovisionadorVM2.sh"
    node.vm.hostname = "VagrantVM2"
  end

  config.vm.define :VagrantVM3 do |node|
    node.vm.box = "bento/ubuntu-20.04"
    node.vm.network :private_network, ip: "192.168.100.4"
    node.vm.provision "shell", path: "aprovisionadorVM3.sh"
    node.vm.hostname = "VagrantVM3"
  end

end
